services:
  webapp:
    build: .
    container_name: moneyshow
    command: ddtrace-run python manage.py runserver 0.0.0.0:8000 # command to run when starting the container
    ports:
      - 8000:8000
    volumes:
      - .:/code
  datadog:
    image: gcr.io/datadoghq/agent:latest
    container_name: dd-agent
    links:
      - webapp
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true # enables agent to receive custom metrics from other containers
      - DD_APM_ENABLED=true # enables tracing
      - DD_APM_NON_LOCAL_TRAFFIC=true # enables agent to receive traces from other containers
      - DD_AGENT_HOST=dd-agent # allows web container to forward traces to agent
      - DD_SITE=datadoghq.eu # determines datadog instance to send data to
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
