# Generated by Django 4.2.9 on 2024-09-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_time_updated',
        ),
    ]
