# Generated by Django 4.2.9 on 2024-09-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_last_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
